INSERT INTO genre (id, title)
VALUES ('3YYHSZMUWWR75DYY2XJIITS4LAS2KSCZP', 'драма');

INSERT INTO genre (id, title)
VALUES ('CB74INE5AU5KGFNKIO3FGI7XB75N53R2V', 'комедия');

INSERT INTO genre (id, title)
VALUES ('MZHPJANCLZTISDBANQHU3DVCZP5EDU3J9', 'фэнтези');

INSERT INTO genre (id, title)
VALUES ('JLEWEWDQITKWSBB2EQKJDDWU3FNAVGZJC', 'приключения');

INSERT INTO genre (id, title)
VALUES ('RD4IXX5HU2CDTW23FL6Z6ZQEOOWQPMU7D', 'аниме');