SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE genre;
TRUNCATE TABLE actor;
TRUNCATE TABLE director;
TRUNCATE TABLE movie;
TRUNCATE TABLE movie_actor;
TRUNCATE TABLE movie_genre;
SET REFERENTIAL_INTEGRITY TRUE;